### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Mo-Fatah** [TheOnlyArtz/rust-tcp-holepunch#1]
I was searching for an implementation for Tcp Holepunch in Rust, and found that yours is really elegant and simple. I found out that this project is not licensed and I would like use your implementation as a base to build upon in another project. Do you allow your code to be reused that way? ( I will mention your code in my project Readme if you allow it)

**Comment by TheOnlyArtz** [comment]
Use it as much as you heart desires.

**Comment by TheOnlyArtz** [comment]
You may want to look at how I've implemented
https://github.com/hopcher
Instead. It's a way better implementation.
The ruby one has client code in it and the js has server code.

Both codes are VERY documented so it will be easy to understand and migrate to rust

**Comment by Mo-Fatah** [comment]
Interesting! Thank you So much :smile:
